# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Add_test(object):
    def setupUi(self, Add_test):
        Add_test.setObjectName("Add_test")
        Add_test.resize(681, 663)
        self.tabWidget = QtWidgets.QTabWidget(Add_test)
        self.tabWidget.setGeometry(QtCore.QRect(11, 11, 661, 342))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.single_point_touch_test = QtWidgets.QWidget()
        self.single_point_touch_test.setObjectName("single_point_touch_test")
        self.gridLayout = QtWidgets.QGridLayout(self.single_point_touch_test)
        self.gridLayout.setObjectName("gridLayout")
        self.single_point_touch_test1 = QtWidgets.QGridLayout()
        self.single_point_touch_test1.setObjectName("single_point_touch_test1")
        self.v_touch_pos_y = QtWidgets.QLineEdit(self.single_point_touch_test)
        self.v_touch_pos_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_touch_pos_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_touch_pos_y.setObjectName("v_touch_pos_y")
        self.single_point_touch_test1.addWidget(self.v_touch_pos_y, 0, 2, 1, 1)
        self.touch_num = QtWidgets.QLabel(self.single_point_touch_test)
        self.touch_num.setObjectName("touch_num")
        self.single_point_touch_test1.addWidget(self.touch_num, 1, 0, 1, 1)
        self.v_touch_pos_x = QtWidgets.QLineEdit(self.single_point_touch_test)
        self.v_touch_pos_x.setMinimumSize(QtCore.QSize(150, 30))
        self.v_touch_pos_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_touch_pos_x.setObjectName("v_touch_pos_x")
        self.single_point_touch_test1.addWidget(self.v_touch_pos_x, 0, 1, 1, 1)
        self.touch_i_time = QtWidgets.QLabel(self.single_point_touch_test)
        self.touch_i_time.setObjectName("touch_i_time")
        self.single_point_touch_test1.addWidget(self.touch_i_time, 2, 0, 1, 1)
        self.v_touch_num = QtWidgets.QLineEdit(self.single_point_touch_test)
        self.v_touch_num.setMinimumSize(QtCore.QSize(0, 30))
        self.v_touch_num.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_touch_num.setObjectName("v_touch_num")
        self.single_point_touch_test1.addWidget(self.v_touch_num, 1, 1, 1, 1)
        self.v_touch_i_time = QtWidgets.QLineEdit(self.single_point_touch_test)
        self.v_touch_i_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_touch_i_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_touch_i_time.setObjectName("v_touch_i_time")
        self.single_point_touch_test1.addWidget(self.v_touch_i_time, 2, 1, 1, 1)
        self.touch_pos = QtWidgets.QLabel(self.single_point_touch_test)
        self.touch_pos.setObjectName("touch_pos")
        self.single_point_touch_test1.addWidget(self.touch_pos, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.single_point_touch_test1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.single_point_touch_test, "")
        self.single_point_press_test = QtWidgets.QWidget()
        self.single_point_press_test.setObjectName("single_point_press_test")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.single_point_press_test)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.single_point_press_test1 = QtWidgets.QGridLayout()
        self.single_point_press_test1.setObjectName("single_point_press_test1")
        self.press_num = QtWidgets.QLabel(self.single_point_press_test)
        self.press_num.setObjectName("press_num")
        self.single_point_press_test1.addWidget(self.press_num, 2, 0, 1, 1)
        self.v_press_pos_y = QtWidgets.QLineEdit(self.single_point_press_test)
        self.v_press_pos_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_pos_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_press_pos_y.setObjectName("v_press_pos_y")
        self.single_point_press_test1.addWidget(self.v_press_pos_y, 0, 2, 1, 1)
        self.v_press_pos_x = QtWidgets.QLineEdit(self.single_point_press_test)
        self.v_press_pos_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_pos_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_press_pos_x.setObjectName("v_press_pos_x")
        self.single_point_press_test1.addWidget(self.v_press_pos_x, 0, 1, 1, 1)
        self.v_press_num = QtWidgets.QLineEdit(self.single_point_press_test)
        self.v_press_num.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_num.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_press_num.setObjectName("v_press_num")
        self.single_point_press_test1.addWidget(self.v_press_num, 2, 1, 1, 1)
        self.press_pos = QtWidgets.QLabel(self.single_point_press_test)
        self.press_pos.setObjectName("press_pos")
        self.single_point_press_test1.addWidget(self.press_pos, 0, 0, 1, 1)
        self.v_press_time = QtWidgets.QLineEdit(self.single_point_press_test)
        self.v_press_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_press_time.setObjectName("v_press_time")
        self.single_point_press_test1.addWidget(self.v_press_time, 1, 1, 1, 1)
        self.press_time = QtWidgets.QLabel(self.single_point_press_test)
        self.press_time.setObjectName("press_time")
        self.single_point_press_test1.addWidget(self.press_time, 1, 0, 1, 1)
        self.v_press_i_time = QtWidgets.QLineEdit(self.single_point_press_test)
        self.v_press_i_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_i_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_press_i_time.setObjectName("v_press_i_time")
        self.single_point_press_test1.addWidget(self.v_press_i_time, 3, 1, 1, 1)
        self.press_i_time = QtWidgets.QLabel(self.single_point_press_test)
        self.press_i_time.setObjectName("press_i_time")
        self.single_point_press_test1.addWidget(self.press_i_time, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.single_point_press_test1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.single_point_press_test, "")
        self.multi_touch_test = QtWidgets.QWidget()
        self.multi_touch_test.setObjectName("multi_touch_test")
        self.v_m_touch_pos_x = QtWidgets.QLineEdit(self.multi_touch_test)
        self.v_m_touch_pos_x.setGeometry(QtCore.QRect(154, 107, 165, 30))
        self.v_m_touch_pos_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_touch_pos_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_m_touch_pos_x.setObjectName("v_m_touch_pos_x")
        self.v_m_touch_loop_num = QtWidgets.QLineEdit(self.multi_touch_test)
        self.v_m_touch_loop_num.setGeometry(QtCore.QRect(154, 239, 165, 30))
        self.v_m_touch_loop_num.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_touch_loop_num.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_m_touch_loop_num.setObjectName("v_m_touch_loop_num")
        self.m_touch_loop_num = QtWidgets.QLabel(self.multi_touch_test)
        self.m_touch_loop_num.setGeometry(QtCore.QRect(12, 239, 90, 16))
        self.m_touch_loop_num.setObjectName("m_touch_loop_num")
        self.m_touch_pos = QtWidgets.QLabel(self.multi_touch_test)
        self.m_touch_pos.setGeometry(QtCore.QRect(12, 107, 116, 16))
        self.m_touch_pos.setObjectName("m_touch_pos")
        self.v_m_touch_i_time = QtWidgets.QLineEdit(self.multi_touch_test)
        self.v_m_touch_i_time.setGeometry(QtCore.QRect(154, 173, 165, 30))
        self.v_m_touch_i_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_touch_i_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_m_touch_i_time.setObjectName("v_m_touch_i_time")
        self.v_m_touch_pos_y = QtWidgets.QLineEdit(self.multi_touch_test)
        self.v_m_touch_pos_y.setGeometry(QtCore.QRect(326, 107, 166, 30))
        self.v_m_touch_pos_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_touch_pos_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_m_touch_pos_y.setObjectName("v_m_touch_pos_y")
        self.m_touch_next_p_b = QtWidgets.QPushButton(self.multi_touch_test)
        self.m_touch_next_p_b.setGeometry(QtCore.QRect(499, 107, 144, 30))
        self.m_touch_next_p_b.setMinimumSize(QtCore.QSize(0, 30))
        self.m_touch_next_p_b.setMaximumSize(QtCore.QSize(16777215, 30))
        self.m_touch_next_p_b.setObjectName("m_touch_next_p_b")
        self.m_touch_i_time = QtWidgets.QLabel(self.multi_touch_test)
        self.m_touch_i_time.setGeometry(QtCore.QRect(12, 173, 135, 16))
        self.m_touch_i_time.setObjectName("m_touch_i_time")
        self.now_point_num = QtWidgets.QLabel(self.multi_touch_test)
        self.now_point_num.setGeometry(QtCore.QRect(70, 40, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.now_point_num.setFont(font)
        self.now_point_num.setAlignment(QtCore.Qt.AlignCenter)
        self.now_point_num.setObjectName("now_point_num")
        self.layoutWidget = QtWidgets.QWidget(self.multi_touch_test)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 431, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.m_touch_point_num = QtWidgets.QLabel(self.layoutWidget)
        self.m_touch_point_num.setObjectName("m_touch_point_num")
        self.horizontalLayout_3.addWidget(self.m_touch_point_num)
        self.v_m_touch_point_num = QtWidgets.QSpinBox(self.layoutWidget)
        self.v_m_touch_point_num.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_touch_point_num.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.v_m_touch_point_num.setFont(font)
        self.v_m_touch_point_num.setMinimum(1)
        self.v_m_touch_point_num.setMaximum(10)
        self.v_m_touch_point_num.setProperty("value", 1)
        self.v_m_touch_point_num.setObjectName("v_m_touch_point_num")
        self.horizontalLayout_3.addWidget(self.v_m_touch_point_num)
        self.confirm_m_touch_point_n_b = QtWidgets.QPushButton(self.layoutWidget)
        self.confirm_m_touch_point_n_b.setMinimumSize(QtCore.QSize(0, 30))
        self.confirm_m_touch_point_n_b.setMaximumSize(QtCore.QSize(16777215, 30))
        self.confirm_m_touch_point_n_b.setObjectName("confirm_m_touch_point_n_b")
        self.horizontalLayout_3.addWidget(self.confirm_m_touch_point_n_b)
        self.tabWidget.addTab(self.multi_touch_test, "")
        self.random_touch_test = QtWidgets.QWidget()
        self.random_touch_test.setObjectName("random_touch_test")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.random_touch_test)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.random_touch_test1 = QtWidgets.QGridLayout()
        self.random_touch_test1.setObjectName("random_touch_test1")
        self.r_touch_p2 = QtWidgets.QLabel(self.random_touch_test)
        self.r_touch_p2.setObjectName("r_touch_p2")
        self.random_touch_test1.addWidget(self.r_touch_p2, 1, 0, 1, 1)
        self.r_touch_p1 = QtWidgets.QLabel(self.random_touch_test)
        self.r_touch_p1.setObjectName("r_touch_p1")
        self.random_touch_test1.addWidget(self.r_touch_p1, 0, 0, 1, 1)
        self.v_r_touch_p2_y = QtWidgets.QLineEdit(self.random_touch_test)
        self.v_r_touch_p2_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_touch_p2_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_touch_p2_y.setObjectName("v_r_touch_p2_y")
        self.random_touch_test1.addWidget(self.v_r_touch_p2_y, 1, 2, 1, 1)
        self.v_r_touch_p2_x = QtWidgets.QLineEdit(self.random_touch_test)
        self.v_r_touch_p2_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_touch_p2_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_touch_p2_x.setObjectName("v_r_touch_p2_x")
        self.random_touch_test1.addWidget(self.v_r_touch_p2_x, 1, 1, 1, 1)
        self.v_r_touch_p1_x = QtWidgets.QLineEdit(self.random_touch_test)
        self.v_r_touch_p1_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_touch_p1_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_touch_p1_x.setObjectName("v_r_touch_p1_x")
        self.random_touch_test1.addWidget(self.v_r_touch_p1_x, 0, 1, 1, 1)
        self.r_touch_num = QtWidgets.QLabel(self.random_touch_test)
        self.r_touch_num.setObjectName("r_touch_num")
        self.random_touch_test1.addWidget(self.r_touch_num, 2, 0, 1, 1)
        self.v_r_touch_p1_y = QtWidgets.QLineEdit(self.random_touch_test)
        self.v_r_touch_p1_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_touch_p1_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_touch_p1_y.setObjectName("v_r_touch_p1_y")
        self.random_touch_test1.addWidget(self.v_r_touch_p1_y, 0, 2, 1, 1)
        self.r_touch_i_time = QtWidgets.QLabel(self.random_touch_test)
        self.r_touch_i_time.setObjectName("r_touch_i_time")
        self.random_touch_test1.addWidget(self.r_touch_i_time, 3, 0, 1, 1)
        self.v_r_touch_i_time = QtWidgets.QLineEdit(self.random_touch_test)
        self.v_r_touch_i_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_touch_i_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_touch_i_time.setObjectName("v_r_touch_i_time")
        self.random_touch_test1.addWidget(self.v_r_touch_i_time, 3, 1, 1, 1)
        self.v_r_touch_num = QtWidgets.QLineEdit(self.random_touch_test)
        self.v_r_touch_num.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_touch_num.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_touch_num.setObjectName("v_r_touch_num")
        self.random_touch_test1.addWidget(self.v_r_touch_num, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.random_touch_test1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.random_touch_test, "")
        self.drag_test = QtWidgets.QWidget()
        self.drag_test.setObjectName("drag_test")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.drag_test)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.drag_test1 = QtWidgets.QGridLayout()
        self.drag_test1.setObjectName("drag_test1")
        self.v_drag_p2_y = QtWidgets.QLineEdit(self.drag_test)
        self.v_drag_p2_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_drag_p2_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_drag_p2_y.setObjectName("v_drag_p2_y")
        self.drag_test1.addWidget(self.v_drag_p2_y, 1, 2, 1, 1)
        self.drag_p1 = QtWidgets.QLabel(self.drag_test)
        self.drag_p1.setObjectName("drag_p1")
        self.drag_test1.addWidget(self.drag_p1, 0, 0, 1, 1)
        self.v_drag_p2_x = QtWidgets.QLineEdit(self.drag_test)
        self.v_drag_p2_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_drag_p2_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_drag_p2_x.setObjectName("v_drag_p2_x")
        self.drag_test1.addWidget(self.v_drag_p2_x, 1, 1, 1, 1)
        self.v_drag_p1_y = QtWidgets.QLineEdit(self.drag_test)
        self.v_drag_p1_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_drag_p1_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_drag_p1_y.setObjectName("v_drag_p1_y")
        self.drag_test1.addWidget(self.v_drag_p1_y, 0, 2, 1, 1)
        self.drag_i_time = QtWidgets.QLabel(self.drag_test)
        self.drag_i_time.setObjectName("drag_i_time")
        self.drag_test1.addWidget(self.drag_i_time, 3, 0, 1, 1)
        self.v_drag_p1_x = QtWidgets.QLineEdit(self.drag_test)
        self.v_drag_p1_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_drag_p1_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_drag_p1_x.setObjectName("v_drag_p1_x")
        self.drag_test1.addWidget(self.v_drag_p1_x, 0, 1, 1, 1)
        self.drag_num = QtWidgets.QLabel(self.drag_test)
        self.drag_num.setObjectName("drag_num")
        self.drag_test1.addWidget(self.drag_num, 2, 0, 1, 1)
        self.v_drag_num = QtWidgets.QLineEdit(self.drag_test)
        self.v_drag_num.setMinimumSize(QtCore.QSize(0, 30))
        self.v_drag_num.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_drag_num.setObjectName("v_drag_num")
        self.drag_test1.addWidget(self.v_drag_num, 2, 1, 1, 1)
        self.drag_p2 = QtWidgets.QLabel(self.drag_test)
        self.drag_p2.setObjectName("drag_p2")
        self.drag_test1.addWidget(self.drag_p2, 1, 0, 1, 1)
        self.v_drag_i_time = QtWidgets.QLineEdit(self.drag_test)
        self.v_drag_i_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_drag_i_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_drag_i_time.setObjectName("v_drag_i_time")
        self.drag_test1.addWidget(self.v_drag_i_time, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.drag_test1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.drag_test, "")
        self.multi_drag_test = QtWidgets.QWidget()
        self.multi_drag_test.setObjectName("multi_drag_test")
        self.now_drag_num = QtWidgets.QLabel(self.multi_drag_test)
        self.now_drag_num.setGeometry(QtCore.QRect(160, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.now_drag_num.setFont(font)
        self.now_drag_num.setAlignment(QtCore.Qt.AlignCenter)
        self.now_drag_num.setObjectName("now_drag_num")
        self.layoutWidget1 = QtWidgets.QWidget(self.multi_drag_test)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 631, 217))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.m_drag_start_p = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_drag_start_p.setFont(font)
        self.m_drag_start_p.setObjectName("m_drag_start_p")
        self.gridLayout_3.addWidget(self.m_drag_start_p, 0, 0, 1, 1)
        self.v_m_drag_start_p_x = QtWidgets.QLineEdit(self.layoutWidget1)
        self.v_m_drag_start_p_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_drag_start_p_x.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.v_m_drag_start_p_x.setFont(font)
        self.v_m_drag_start_p_x.setObjectName("v_m_drag_start_p_x")
        self.gridLayout_3.addWidget(self.v_m_drag_start_p_x, 0, 1, 1, 1)
        self.v_m_drag_start_p_y = QtWidgets.QLineEdit(self.layoutWidget1)
        self.v_m_drag_start_p_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_drag_start_p_y.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.v_m_drag_start_p_y.setFont(font)
        self.v_m_drag_start_p_y.setObjectName("v_m_drag_start_p_y")
        self.gridLayout_3.addWidget(self.v_m_drag_start_p_y, 0, 2, 1, 1)
        self.m_drag_end_p = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_drag_end_p.setFont(font)
        self.m_drag_end_p.setObjectName("m_drag_end_p")
        self.gridLayout_3.addWidget(self.m_drag_end_p, 1, 0, 1, 1)
        self.v_m_drag_end_p_x = QtWidgets.QLineEdit(self.layoutWidget1)
        self.v_m_drag_end_p_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_drag_end_p_x.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.v_m_drag_end_p_x.setFont(font)
        self.v_m_drag_end_p_x.setObjectName("v_m_drag_end_p_x")
        self.gridLayout_3.addWidget(self.v_m_drag_end_p_x, 1, 1, 1, 1)
        self.v_m_drag_end_p_y = QtWidgets.QLineEdit(self.layoutWidget1)
        self.v_m_drag_end_p_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_drag_end_p_y.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.v_m_drag_end_p_y.setFont(font)
        self.v_m_drag_end_p_y.setObjectName("v_m_drag_end_p_y")
        self.gridLayout_3.addWidget(self.v_m_drag_end_p_y, 1, 2, 1, 1)
        self.m_drag_next_b = QtWidgets.QPushButton(self.layoutWidget1)
        self.m_drag_next_b.setMinimumSize(QtCore.QSize(0, 30))
        self.m_drag_next_b.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_drag_next_b.setFont(font)
        self.m_drag_next_b.setObjectName("m_drag_next_b")
        self.gridLayout_3.addWidget(self.m_drag_next_b, 1, 3, 1, 1)
        self.m_drag_loop_num = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_drag_loop_num.setFont(font)
        self.m_drag_loop_num.setObjectName("m_drag_loop_num")
        self.gridLayout_3.addWidget(self.m_drag_loop_num, 2, 0, 1, 1)
        self.v_m_drag_loop_num = QtWidgets.QLineEdit(self.layoutWidget1)
        self.v_m_drag_loop_num.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_drag_loop_num.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.v_m_drag_loop_num.setFont(font)
        self.v_m_drag_loop_num.setObjectName("v_m_drag_loop_num")
        self.gridLayout_3.addWidget(self.v_m_drag_loop_num, 2, 1, 1, 1)
        self.m_drag_i_time = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_drag_i_time.setFont(font)
        self.m_drag_i_time.setObjectName("m_drag_i_time")
        self.gridLayout_3.addWidget(self.m_drag_i_time, 3, 0, 1, 1)
        self.v_m_drag_i_time = QtWidgets.QLineEdit(self.layoutWidget1)
        self.v_m_drag_i_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_drag_i_time.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.v_m_drag_i_time.setFont(font)
        self.v_m_drag_i_time.setObjectName("v_m_drag_i_time")
        self.gridLayout_3.addWidget(self.v_m_drag_i_time, 3, 1, 1, 1)
        self.m_drag_time = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_drag_time.setFont(font)
        self.m_drag_time.setObjectName("m_drag_time")
        self.gridLayout_3.addWidget(self.m_drag_time, 4, 0, 1, 1)
        self.v_m_drag_time = QtWidgets.QLineEdit(self.layoutWidget1)
        self.v_m_drag_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_drag_time.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.v_m_drag_time.setFont(font)
        self.v_m_drag_time.setObjectName("v_m_drag_time")
        self.gridLayout_3.addWidget(self.v_m_drag_time, 4, 1, 1, 1)
        self.m_drag_trip_i_time = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_drag_trip_i_time.setFont(font)
        self.m_drag_trip_i_time.setObjectName("m_drag_trip_i_time")
        self.gridLayout_3.addWidget(self.m_drag_trip_i_time, 5, 0, 1, 1)
        self.v_m_drag_trip_i_time = QtWidgets.QLineEdit(self.layoutWidget1)
        self.v_m_drag_trip_i_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_m_drag_trip_i_time.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.v_m_drag_trip_i_time.setFont(font)
        self.v_m_drag_trip_i_time.setObjectName("v_m_drag_trip_i_time")
        self.gridLayout_3.addWidget(self.v_m_drag_trip_i_time, 5, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.multi_drag_test)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 511, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.m_drag_num = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_drag_num.setFont(font)
        self.m_drag_num.setObjectName("m_drag_num")
        self.horizontalLayout_4.addWidget(self.m_drag_num)
        self.v_m_drag_num = QtWidgets.QSpinBox(self.layoutWidget2)
        self.v_m_drag_num.setMinimumSize(QtCore.QSize(144, 30))
        self.v_m_drag_num.setMaximumSize(QtCore.QSize(144, 144))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.v_m_drag_num.setFont(font)
        self.v_m_drag_num.setMinimum(1)
        self.v_m_drag_num.setMaximum(10)
        self.v_m_drag_num.setProperty("value", 1)
        self.v_m_drag_num.setObjectName("v_m_drag_num")
        self.horizontalLayout_4.addWidget(self.v_m_drag_num)
        self.confirm_m_drag_n_b = QtWidgets.QPushButton(self.layoutWidget2)
        self.confirm_m_drag_n_b.setMinimumSize(QtCore.QSize(0, 30))
        self.confirm_m_drag_n_b.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.confirm_m_drag_n_b.setFont(font)
        self.confirm_m_drag_n_b.setObjectName("confirm_m_drag_n_b")
        self.horizontalLayout_4.addWidget(self.confirm_m_drag_n_b)
        self.tabWidget.addTab(self.multi_drag_test, "")
        self.random_drag_test = QtWidgets.QWidget()
        self.random_drag_test.setObjectName("random_drag_test")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.random_drag_test)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.random_drag_test1 = QtWidgets.QGridLayout()
        self.random_drag_test1.setObjectName("random_drag_test1")
        self.v_r_drag_time = QtWidgets.QLineEdit(self.random_drag_test)
        self.v_r_drag_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_drag_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_drag_time.setObjectName("v_r_drag_time")
        self.random_drag_test1.addWidget(self.v_r_drag_time, 4, 1, 1, 1)
        self.r_drag_time = QtWidgets.QLabel(self.random_drag_test)
        self.r_drag_time.setObjectName("r_drag_time")
        self.random_drag_test1.addWidget(self.r_drag_time, 4, 0, 1, 1)
        self.v_r_drag_end_p_y = QtWidgets.QLineEdit(self.random_drag_test)
        self.v_r_drag_end_p_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_drag_end_p_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_drag_end_p_y.setObjectName("v_r_drag_end_p_y")
        self.random_drag_test1.addWidget(self.v_r_drag_end_p_y, 1, 2, 1, 1)
        self.v_r_drag_end_p_x = QtWidgets.QLineEdit(self.random_drag_test)
        self.v_r_drag_end_p_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_drag_end_p_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_drag_end_p_x.setObjectName("v_r_drag_end_p_x")
        self.random_drag_test1.addWidget(self.v_r_drag_end_p_x, 1, 1, 1, 1)
        self.v_r_drag_start_p_y = QtWidgets.QLineEdit(self.random_drag_test)
        self.v_r_drag_start_p_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_drag_start_p_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_drag_start_p_y.setObjectName("v_r_drag_start_p_y")
        self.random_drag_test1.addWidget(self.v_r_drag_start_p_y, 0, 2, 1, 1)
        self.v_r_drag_num = QtWidgets.QLineEdit(self.random_drag_test)
        self.v_r_drag_num.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_drag_num.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_drag_num.setObjectName("v_r_drag_num")
        self.random_drag_test1.addWidget(self.v_r_drag_num, 2, 1, 1, 1)
        self.r_drag_i_time = QtWidgets.QLabel(self.random_drag_test)
        self.r_drag_i_time.setObjectName("r_drag_i_time")
        self.random_drag_test1.addWidget(self.r_drag_i_time, 3, 0, 1, 1)
        self.v_r_drag_start_p_x = QtWidgets.QLineEdit(self.random_drag_test)
        self.v_r_drag_start_p_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_drag_start_p_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_drag_start_p_x.setObjectName("v_r_drag_start_p_x")
        self.random_drag_test1.addWidget(self.v_r_drag_start_p_x, 0, 1, 1, 1)
        self.r_drag_num = QtWidgets.QLabel(self.random_drag_test)
        self.r_drag_num.setObjectName("r_drag_num")
        self.random_drag_test1.addWidget(self.r_drag_num, 2, 0, 1, 1)
        self.r_drag_end_p = QtWidgets.QLabel(self.random_drag_test)
        self.r_drag_end_p.setObjectName("r_drag_end_p")
        self.random_drag_test1.addWidget(self.r_drag_end_p, 1, 0, 1, 1)
        self.v_r_drag_i_time = QtWidgets.QLineEdit(self.random_drag_test)
        self.v_r_drag_i_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_r_drag_i_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.v_r_drag_i_time.setObjectName("v_r_drag_i_time")
        self.random_drag_test1.addWidget(self.v_r_drag_i_time, 3, 1, 1, 1)
        self.r_drag_start_p = QtWidgets.QLabel(self.random_drag_test)
        self.r_drag_start_p.setObjectName("r_drag_start_p")
        self.random_drag_test1.addWidget(self.r_drag_start_p, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.random_drag_test1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.random_drag_test, "")
        self.press_drag_test = QtWidgets.QWidget()
        self.press_drag_test.setObjectName("press_drag_test")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.press_drag_test)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.press_drag_test1 = QtWidgets.QGridLayout()
        self.press_drag_test1.setObjectName("press_drag_test1")
        self.press_drag_i_time = QtWidgets.QLabel(self.press_drag_test)
        self.press_drag_i_time.setObjectName("press_drag_i_time")
        self.press_drag_test1.addWidget(self.press_drag_i_time, 5, 0, 1, 1)
        self.press_drag_d_time = QtWidgets.QLabel(self.press_drag_test)
        self.press_drag_d_time.setObjectName("press_drag_d_time")
        self.press_drag_test1.addWidget(self.press_drag_d_time, 4, 0, 1, 1)
        self.press_drag_p_time = QtWidgets.QLabel(self.press_drag_test)
        self.press_drag_p_time.setObjectName("press_drag_p_time")
        self.press_drag_test1.addWidget(self.press_drag_p_time, 3, 0, 1, 1)
        self.v_press_drag_p_time_2 = QtWidgets.QLineEdit(self.press_drag_test)
        self.v_press_drag_p_time_2.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_drag_p_time_2.setObjectName("v_press_drag_p_time_2")
        self.press_drag_test1.addWidget(self.v_press_drag_p_time_2, 4, 1, 1, 1)
        self.v_press_drag_p_time = QtWidgets.QLineEdit(self.press_drag_test)
        self.v_press_drag_p_time.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_drag_p_time.setObjectName("v_press_drag_p_time")
        self.press_drag_test1.addWidget(self.v_press_drag_p_time, 3, 1, 1, 1)
        self.v_press_drag_num = QtWidgets.QLineEdit(self.press_drag_test)
        self.v_press_drag_num.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_drag_num.setObjectName("v_press_drag_num")
        self.press_drag_test1.addWidget(self.v_press_drag_num, 2, 1, 1, 1)
        self.v_press_drag_end_p_y = QtWidgets.QLineEdit(self.press_drag_test)
        self.v_press_drag_end_p_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_drag_end_p_y.setObjectName("v_press_drag_end_p_y")
        self.press_drag_test1.addWidget(self.v_press_drag_end_p_y, 1, 2, 1, 1)
        self.v_press_drag_end_p_x = QtWidgets.QLineEdit(self.press_drag_test)
        self.v_press_drag_end_p_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_drag_end_p_x.setObjectName("v_press_drag_end_p_x")
        self.press_drag_test1.addWidget(self.v_press_drag_end_p_x, 1, 1, 1, 1)
        self.v_press_drag_start_p_y = QtWidgets.QLineEdit(self.press_drag_test)
        self.v_press_drag_start_p_y.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_drag_start_p_y.setObjectName("v_press_drag_start_p_y")
        self.press_drag_test1.addWidget(self.v_press_drag_start_p_y, 0, 2, 1, 1)
        self.press_drag_start_p = QtWidgets.QLabel(self.press_drag_test)
        self.press_drag_start_p.setObjectName("press_drag_start_p")
        self.press_drag_test1.addWidget(self.press_drag_start_p, 0, 0, 1, 1)
        self.v_press_drag_p_time_3 = QtWidgets.QLineEdit(self.press_drag_test)
        self.v_press_drag_p_time_3.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_drag_p_time_3.setObjectName("v_press_drag_p_time_3")
        self.press_drag_test1.addWidget(self.v_press_drag_p_time_3, 5, 1, 1, 1)
        self.press_drag_num = QtWidgets.QLabel(self.press_drag_test)
        self.press_drag_num.setObjectName("press_drag_num")
        self.press_drag_test1.addWidget(self.press_drag_num, 2, 0, 1, 1)
        self.v_press_drag_start_p_x = QtWidgets.QLineEdit(self.press_drag_test)
        self.v_press_drag_start_p_x.setMinimumSize(QtCore.QSize(0, 30))
        self.v_press_drag_start_p_x.setObjectName("v_press_drag_start_p_x")
        self.press_drag_test1.addWidget(self.v_press_drag_start_p_x, 0, 1, 1, 1)
        self.press_drag_end_p = QtWidgets.QLabel(self.press_drag_test)
        self.press_drag_end_p.setObjectName("press_drag_end_p")
        self.press_drag_test1.addWidget(self.press_drag_end_p, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.press_drag_test1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.press_drag_test, "")
        self.layoutWidget3 = QtWidgets.QWidget(Add_test)
        self.layoutWidget3.setGeometry(QtCore.QRect(410, 610, 264, 42))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete_test_b = QtWidgets.QPushButton(self.layoutWidget3)
        self.delete_test_b.setMinimumSize(QtCore.QSize(0, 40))
        self.delete_test_b.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.delete_test_b.setFont(font)
        self.delete_test_b.setObjectName("delete_test_b")
        self.horizontalLayout.addWidget(self.delete_test_b)
        self.finish_b = QtWidgets.QPushButton(self.layoutWidget3)
        self.finish_b.setMinimumSize(QtCore.QSize(0, 40))
        self.finish_b.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.finish_b.setFont(font)
        self.finish_b.setObjectName("finish_b")
        self.horizontalLayout.addWidget(self.finish_b)
        self.groupBox = QtWidgets.QGroupBox(Add_test)
        self.groupBox.setGeometry(QtCore.QRect(10, 400, 661, 201))
        self.groupBox.setObjectName("groupBox")
        self.currentQueueList = QtWidgets.QListWidget(self.groupBox)
        self.currentQueueList.setGeometry(QtCore.QRect(10, 20, 641, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.currentQueueList.setFont(font)
        self.currentQueueList.setObjectName("currentQueueList")
        item = QtWidgets.QListWidgetItem()
        self.currentQueueList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.currentQueueList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.currentQueueList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.currentQueueList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.currentQueueList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.currentQueueList.addItem(item)
        self.layoutWidget4 = QtWidgets.QWidget(Add_test)
        self.layoutWidget4.setGeometry(QtCore.QRect(420, 360, 243, 42))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clear_test_b = QtWidgets.QPushButton(self.layoutWidget4)
        self.clear_test_b.setMinimumSize(QtCore.QSize(0, 40))
        self.clear_test_b.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.clear_test_b.setFont(font)
        self.clear_test_b.setObjectName("clear_test_b")
        self.horizontalLayout_2.addWidget(self.clear_test_b)
        self.test_add_b = QtWidgets.QPushButton(self.layoutWidget4)
        self.test_add_b.setMinimumSize(QtCore.QSize(0, 40))
        self.test_add_b.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.test_add_b.setFont(font)
        self.test_add_b.setObjectName("test_add_b")
        self.horizontalLayout_2.addWidget(self.test_add_b)

        self.retranslateUi(Add_test)
        self.tabWidget.setCurrentIndex(0)
        self.delete_test_b.clicked.connect(Add_test.delete_current_row)
        self.clear_test_b.clicked.connect(self.v_touch_i_time.clear)
        self.clear_test_b.clicked.connect(self.v_touch_num.clear)
        self.clear_test_b.clicked.connect(self.v_touch_pos_x.clear)
        self.clear_test_b.clicked.connect(self.v_touch_pos_y.clear)
        self.clear_test_b.clicked.connect(self.v_press_pos_x.clear)
        self.clear_test_b.clicked.connect(self.v_press_time.clear)
        self.clear_test_b.clicked.connect(self.v_press_num.clear)
        self.clear_test_b.clicked.connect(self.v_press_i_time.clear)
        self.clear_test_b.clicked.connect(self.v_press_pos_y.clear)
        self.clear_test_b.clicked.connect(self.v_r_touch_p1_x.clear)
        self.clear_test_b.clicked.connect(self.v_r_touch_p2_x.clear)
        self.clear_test_b.clicked.connect(self.v_r_touch_num.clear)
        self.clear_test_b.clicked.connect(self.v_r_touch_i_time.clear)
        self.clear_test_b.clicked.connect(self.v_r_touch_p1_y.clear)
        self.clear_test_b.clicked.connect(self.v_r_touch_p2_y.clear)
        self.clear_test_b.clicked.connect(self.v_m_touch_pos_x.clear)
        self.clear_test_b.clicked.connect(self.v_m_touch_pos_y.clear)
        self.clear_test_b.clicked.connect(self.v_m_touch_i_time.clear)
        self.clear_test_b.clicked.connect(self.v_m_touch_loop_num.clear)
        self.clear_test_b.clicked.connect(self.v_drag_p1_x.clear)
        self.clear_test_b.clicked.connect(self.v_drag_p1_y.clear)
        self.clear_test_b.clicked.connect(self.v_drag_p2_x.clear)
        self.clear_test_b.clicked.connect(self.v_drag_p2_y.clear)
        self.clear_test_b.clicked.connect(self.v_drag_num.clear)
        self.clear_test_b.clicked.connect(self.v_drag_i_time.clear)
        self.clear_test_b.clicked.connect(self.v_m_drag_start_p_x.clear)
        self.clear_test_b.clicked.connect(self.v_m_drag_start_p_y.clear)
        self.clear_test_b.clicked.connect(self.v_m_drag_end_p_x.clear)
        self.clear_test_b.clicked.connect(self.v_m_drag_end_p_y.clear)
        self.clear_test_b.clicked.connect(self.v_m_drag_loop_num.clear)
        self.clear_test_b.clicked.connect(self.v_m_drag_i_time.clear)
        self.clear_test_b.clicked.connect(self.v_m_drag_time.clear)
        self.clear_test_b.clicked.connect(self.v_m_drag_trip_i_time.clear)
        self.clear_test_b.clicked.connect(self.v_r_drag_start_p_x.clear)
        self.clear_test_b.clicked.connect(self.v_r_drag_start_p_y.clear)
        self.clear_test_b.clicked.connect(self.v_r_drag_end_p_x.clear)
        self.clear_test_b.clicked.connect(self.v_r_drag_end_p_y.clear)
        self.clear_test_b.clicked.connect(self.v_r_drag_num.clear)
        self.clear_test_b.clicked.connect(self.v_r_drag_i_time.clear)
        self.clear_test_b.clicked.connect(self.v_r_drag_time.clear)
        self.clear_test_b.clicked.connect(self.v_press_drag_start_p_x.clear)
        self.clear_test_b.clicked.connect(self.v_press_drag_start_p_y.clear)
        self.clear_test_b.clicked.connect(self.v_press_drag_end_p_x.clear)
        self.clear_test_b.clicked.connect(self.v_press_drag_end_p_y.clear)
        self.clear_test_b.clicked.connect(self.v_press_drag_num.clear)
        self.clear_test_b.clicked.connect(self.v_press_drag_p_time.clear)
        self.clear_test_b.clicked.connect(self.v_press_drag_p_time_2.clear)
        self.clear_test_b.clicked.connect(self.v_press_drag_p_time_3.clear)
        self.m_touch_next_p_b.clicked.connect(Add_test.mul_touch_next_p)
        self.confirm_m_touch_point_n_b.clicked.connect(self.v_m_touch_point_num.hide)
        self.confirm_m_touch_point_n_b.clicked.connect(self.now_point_num.show)
        self.confirm_m_touch_point_n_b.clicked.connect(self.confirm_m_touch_point_n_b.hide)
        self.confirm_m_touch_point_n_b.clicked.connect(Add_test.confirm_m_touch_p_num)
        self.clear_test_b.clicked.connect(self.confirm_m_touch_point_n_b.show)
        self.clear_test_b.clicked.connect(self.now_point_num.hide)
        self.confirm_m_drag_n_b.clicked.connect(self.now_drag_num.show)
        self.confirm_m_drag_n_b.clicked.connect(self.v_m_drag_num.hide)
        self.confirm_m_drag_n_b.clicked.connect(self.confirm_m_drag_n_b.hide)
        self.clear_test_b.clicked.connect(self.now_drag_num.hide)
        self.clear_test_b.clicked.connect(self.v_m_drag_num.show)
        self.clear_test_b.clicked.connect(self.confirm_m_drag_n_b.show)
        self.confirm_m_drag_n_b.clicked.connect(Add_test.confirm_m_drag_num)
        self.clear_test_b.clicked.connect(self.v_m_touch_point_num.show)
        self.m_drag_next_b.clicked.connect(Add_test.mul_drag_next_l)
        self.clear_test_b.clicked.connect(Add_test.reset_point_no)
        self.clear_test_b.clicked.connect(Add_test.reset_drag_no)
        self.test_add_b.clicked.connect(Add_test.add_new_test_b)
        self.finish_b.clicked.connect(Add_test.fin_queue_edit)
        QtCore.QMetaObject.connectSlotsByName(Add_test)
        Add_test.setTabOrder(self.v_r_drag_start_p_x, self.v_touch_pos_y)
        Add_test.setTabOrder(self.v_touch_pos_y, self.v_touch_num)
        Add_test.setTabOrder(self.v_touch_num, self.v_touch_i_time)
        Add_test.setTabOrder(self.v_touch_i_time, self.v_press_pos_x)
        Add_test.setTabOrder(self.v_press_pos_x, self.v_press_pos_y)
        Add_test.setTabOrder(self.v_press_pos_y, self.v_press_time)
        Add_test.setTabOrder(self.v_press_time, self.v_press_num)
        Add_test.setTabOrder(self.v_press_num, self.v_press_i_time)
        Add_test.setTabOrder(self.v_press_i_time, self.v_m_touch_point_num)
        Add_test.setTabOrder(self.v_m_touch_point_num, self.v_m_touch_pos_x)
        Add_test.setTabOrder(self.v_m_touch_pos_x, self.v_m_touch_pos_y)
        Add_test.setTabOrder(self.v_m_touch_pos_y, self.v_m_touch_i_time)
        Add_test.setTabOrder(self.v_m_touch_i_time, self.v_m_touch_loop_num)
        Add_test.setTabOrder(self.v_m_touch_loop_num, self.v_r_touch_p1_x)
        Add_test.setTabOrder(self.v_r_touch_p1_x, self.v_r_touch_p1_y)
        Add_test.setTabOrder(self.v_r_touch_p1_y, self.v_r_touch_p2_x)
        Add_test.setTabOrder(self.v_r_touch_p2_x, self.v_r_touch_p2_y)
        Add_test.setTabOrder(self.v_r_touch_p2_y, self.v_r_touch_num)
        Add_test.setTabOrder(self.v_r_touch_num, self.v_r_touch_i_time)
        Add_test.setTabOrder(self.v_r_touch_i_time, self.v_drag_p1_x)
        Add_test.setTabOrder(self.v_drag_p1_x, self.v_drag_p1_y)
        Add_test.setTabOrder(self.v_drag_p1_y, self.v_drag_p2_x)
        Add_test.setTabOrder(self.v_drag_p2_x, self.v_drag_p2_y)
        Add_test.setTabOrder(self.v_drag_p2_y, self.v_drag_num)
        Add_test.setTabOrder(self.v_drag_num, self.v_drag_i_time)
        Add_test.setTabOrder(self.v_drag_i_time, self.v_m_drag_num)
        Add_test.setTabOrder(self.v_m_drag_num, self.confirm_m_drag_n_b)
        Add_test.setTabOrder(self.confirm_m_drag_n_b, self.v_m_drag_start_p_x)
        Add_test.setTabOrder(self.v_m_drag_start_p_x, self.v_m_drag_start_p_y)
        Add_test.setTabOrder(self.v_m_drag_start_p_y, self.v_m_drag_end_p_x)
        Add_test.setTabOrder(self.v_m_drag_end_p_x, self.v_m_drag_end_p_y)
        Add_test.setTabOrder(self.v_m_drag_end_p_y, self.v_m_drag_loop_num)
        Add_test.setTabOrder(self.v_m_drag_loop_num, self.v_m_drag_i_time)
        Add_test.setTabOrder(self.v_m_drag_i_time, self.v_m_drag_time)
        Add_test.setTabOrder(self.v_m_drag_time, self.v_m_drag_trip_i_time)
        Add_test.setTabOrder(self.v_m_drag_trip_i_time, self.v_press_drag_p_time_3)
        Add_test.setTabOrder(self.v_press_drag_p_time_3, self.v_press_drag_p_time)
        Add_test.setTabOrder(self.v_press_drag_p_time, self.v_press_drag_p_time_2)
        Add_test.setTabOrder(self.v_press_drag_p_time_2, self.m_drag_next_b)
        Add_test.setTabOrder(self.m_drag_next_b, self.v_press_drag_start_p_x)
        Add_test.setTabOrder(self.v_press_drag_start_p_x, self.delete_test_b)
        Add_test.setTabOrder(self.delete_test_b, self.currentQueueList)
        Add_test.setTabOrder(self.currentQueueList, self.finish_b)
        Add_test.setTabOrder(self.finish_b, self.tabWidget)
        Add_test.setTabOrder(self.tabWidget, self.clear_test_b)
        Add_test.setTabOrder(self.clear_test_b, self.test_add_b)
        Add_test.setTabOrder(self.test_add_b, self.v_r_drag_time)
        Add_test.setTabOrder(self.v_r_drag_time, self.v_r_drag_end_p_x)
        Add_test.setTabOrder(self.v_r_drag_end_p_x, self.m_touch_next_p_b)
        Add_test.setTabOrder(self.m_touch_next_p_b, self.v_r_drag_start_p_y)
        Add_test.setTabOrder(self.v_r_drag_start_p_y, self.v_press_drag_num)
        Add_test.setTabOrder(self.v_press_drag_num, self.v_touch_pos_x)
        Add_test.setTabOrder(self.v_touch_pos_x, self.confirm_m_touch_point_n_b)
        Add_test.setTabOrder(self.confirm_m_touch_point_n_b, self.v_press_drag_end_p_x)
        Add_test.setTabOrder(self.v_press_drag_end_p_x, self.v_press_drag_start_p_y)
        Add_test.setTabOrder(self.v_press_drag_start_p_y, self.v_r_drag_i_time)
        Add_test.setTabOrder(self.v_r_drag_i_time, self.v_r_drag_num)
        Add_test.setTabOrder(self.v_r_drag_num, self.v_press_drag_end_p_y)
        Add_test.setTabOrder(self.v_press_drag_end_p_y, self.v_r_drag_end_p_y)

    def retranslateUi(self, Add_test):
        _translate = QtCore.QCoreApplication.translate
        Add_test.setWindowTitle(_translate("Add_test", "Dialog"))
        self.touch_num.setText(_translate("Add_test", "点击的次数："))
        self.touch_i_time.setText(_translate("Add_test", "两次点击间隔时间："))
        self.touch_pos.setText(_translate("Add_test", "点的坐标:(X,Y)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.single_point_touch_test), _translate("Add_test", "单点点击测试"))
        self.press_num.setText(_translate("Add_test", "长按的次数："))
        self.press_pos.setText(_translate("Add_test", "点的坐标:(X,Y)"))
        self.press_time.setText(_translate("Add_test", "长按持续时间"))
        self.press_i_time.setText(_translate("Add_test", "两次长按间隔时间："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.single_point_press_test), _translate("Add_test", "单点长按测试"))
        self.m_touch_loop_num.setText(_translate("Add_test", "循环的遍数："))
        self.m_touch_pos.setText(_translate("Add_test", "第1点坐标:(X,Y)"))
        self.m_touch_next_p_b.setText(_translate("Add_test", "确认并输入下一个点"))
        self.m_touch_i_time.setText(_translate("Add_test", "两次点击间隔时间："))
        self.now_point_num.setText(_translate("Add_test", "1"))
        self.m_touch_point_num.setText(_translate("Add_test", "点击点的个数："))
        self.confirm_m_touch_point_n_b.setText(_translate("Add_test", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.multi_touch_test), _translate("Add_test", "多点点击测试"))
        self.r_touch_p2.setText(_translate("Add_test", "点2坐标：(X,Y)"))
        self.r_touch_p1.setText(_translate("Add_test", "点1坐标：(X,Y)"))
        self.r_touch_num.setText(_translate("Add_test", "点击次数："))
        self.r_touch_i_time.setText(_translate("Add_test", "两次点击间隔时间："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.random_touch_test), _translate("Add_test", "随机点击测试"))
        self.drag_p1.setText(_translate("Add_test", "点1坐标："))
        self.drag_i_time.setText(_translate("Add_test", "两次滑动间隔时间："))
        self.drag_num.setText(_translate("Add_test", "滑动次数："))
        self.drag_p2.setText(_translate("Add_test", "点2坐标："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.drag_test), _translate("Add_test", "单线滑动测试"))
        self.now_drag_num.setText(_translate("Add_test", "1"))
        self.m_drag_start_p.setText(_translate("Add_test", "第1次滑动起点坐标:(X,Y)"))
        self.m_drag_end_p.setText(_translate("Add_test", "第1次滑动终点坐标:(X,Y)"))
        self.m_drag_next_b.setText(_translate("Add_test", "确认并输入下次滑动"))
        self.m_drag_loop_num.setText(_translate("Add_test", "滑动循环的遍数："))
        self.m_drag_i_time.setText(_translate("Add_test", "两次滑动间隔时间："))
        self.m_drag_time.setText(_translate("Add_test", "每次滑动持续时间："))
        self.m_drag_trip_i_time.setText(_translate("Add_test", "两遍滑动间隔时间："))
        self.m_drag_num.setText(_translate("Add_test", "一遍内滑动的次数："))
        self.confirm_m_drag_n_b.setText(_translate("Add_test", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.multi_drag_test), _translate("Add_test", "多线滑动测试"))
        self.r_drag_time.setText(_translate("Add_test", "滑动时间："))
        self.r_drag_i_time.setText(_translate("Add_test", "两次滑动间隔时间："))
        self.r_drag_num.setText(_translate("Add_test", "滑动次数："))
        self.r_drag_end_p.setText(_translate("Add_test", "点2坐标：(X,Y)"))
        self.r_drag_start_p.setText(_translate("Add_test", "点1坐标：(X,Y)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.random_drag_test), _translate("Add_test", "随机滑动测试"))
        self.press_drag_i_time.setText(_translate("Add_test", "两次动作间隔时间："))
        self.press_drag_d_time.setText(_translate("Add_test", "滑动时间："))
        self.press_drag_p_time.setText(_translate("Add_test", "长按时间："))
        self.press_drag_start_p.setText(_translate("Add_test", "按住点的坐标：(X,Y)"))
        self.press_drag_num.setText(_translate("Add_test", "长按滑动次数："))
        self.press_drag_end_p.setText(_translate("Add_test", "终点坐标：(X,Y)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.press_drag_test), _translate("Add_test", "长按滑动测试"))
        self.delete_test_b.setText(_translate("Add_test", "删除"))
        self.finish_b.setText(_translate("Add_test", " 测试队列创建完成"))
        self.groupBox.setTitle(_translate("Add_test", "当前测试队列"))
        __sortingEnabled = self.currentQueueList.isSortingEnabled()
        self.currentQueueList.setSortingEnabled(False)
        item = self.currentQueueList.item(0)
        item.setText(_translate("Add_test", "New Item"))
        item = self.currentQueueList.item(1)
        item.setText(_translate("Add_test", "New Item"))
        item = self.currentQueueList.item(2)
        item.setText(_translate("Add_test", "New Item"))
        item = self.currentQueueList.item(3)
        item.setText(_translate("Add_test", "4564565"))
        item = self.currentQueueList.item(4)
        item.setText(_translate("Add_test", "23"))
        item = self.currentQueueList.item(5)
        item.setText(_translate("Add_test", "New Item"))
        self.currentQueueList.setSortingEnabled(__sortingEnabled)
        self.clear_test_b.setText(_translate("Add_test", "清除参数"))
        self.test_add_b.setText(_translate("Add_test", "加入测试队列"))

