# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'in_device_infor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_In_dev_infor(object):
    def setupUi(self, In_dev_infor):
        In_dev_infor.setObjectName("In_dev_infor")
        In_dev_infor.resize(784, 278)
        self.gridLayout = QtWidgets.QGridLayout(In_dev_infor)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.reso_x = QtWidgets.QLabel(In_dev_infor)
        self.reso_x.setObjectName("reso_x")
        self.verticalLayout_2.addWidget(self.reso_x)
        self.reso_y = QtWidgets.QLabel(In_dev_infor)
        self.reso_y.setObjectName("reso_y")
        self.verticalLayout_2.addWidget(self.reso_y)
        self.p_name = QtWidgets.QLabel(In_dev_infor)
        self.p_name.setObjectName("p_name")
        self.verticalLayout_2.addWidget(self.p_name)
        self.a_name = QtWidgets.QLabel(In_dev_infor)
        self.a_name.setObjectName("a_name")
        self.verticalLayout_2.addWidget(self.a_name)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(27)
        self.verticalLayout.setObjectName("verticalLayout")
        self.v_reso_x = QtWidgets.QLineEdit(In_dev_infor)
        self.v_reso_x.setMinimumSize(QtCore.QSize(200, 30))
        self.v_reso_x.setMaximumSize(QtCore.QSize(200, 30))
        self.v_reso_x.setObjectName("v_reso_x")
        self.verticalLayout.addWidget(self.v_reso_x)
        self.v_reso_y = QtWidgets.QLineEdit(In_dev_infor)
        self.v_reso_y.setMinimumSize(QtCore.QSize(200, 30))
        self.v_reso_y.setMaximumSize(QtCore.QSize(200, 30))
        self.v_reso_y.setObjectName("v_reso_y")
        self.verticalLayout.addWidget(self.v_reso_y)
        self.v_p_name = QtWidgets.QLineEdit(In_dev_infor)
        self.v_p_name.setMinimumSize(QtCore.QSize(639, 30))
        self.v_p_name.setMaximumSize(QtCore.QSize(639, 30))
        self.v_p_name.setObjectName("v_p_name")
        self.verticalLayout.addWidget(self.v_p_name)
        self.v_a_name = QtWidgets.QLineEdit(In_dev_infor)
        self.v_a_name.setMinimumSize(QtCore.QSize(639, 30))
        self.v_a_name.setMaximumSize(QtCore.QSize(639, 30))
        self.v_a_name.setObjectName("v_a_name")
        self.verticalLayout.addWidget(self.v_a_name)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.frame = QtWidgets.QFrame(In_dev_infor)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fin_b = QtWidgets.QPushButton(In_dev_infor)
        self.fin_b.setMinimumSize(QtCore.QSize(110, 30))
        self.fin_b.setMaximumSize(QtCore.QSize(110, 30))
        self.fin_b.setObjectName("fin_b")
        self.horizontalLayout_2.addWidget(self.fin_b)
        self.exit_b = QtWidgets.QPushButton(In_dev_infor)
        self.exit_b.setMinimumSize(QtCore.QSize(110, 30))
        self.exit_b.setMaximumSize(QtCore.QSize(110, 30))
        self.exit_b.setObjectName("exit_b")
        self.horizontalLayout_2.addWidget(self.exit_b)
        self.clean_b = QtWidgets.QPushButton(In_dev_infor)
        self.clean_b.setMinimumSize(QtCore.QSize(110, 30))
        self.clean_b.setMaximumSize(QtCore.QSize(110, 30))
        self.clean_b.setObjectName("clean_b")
        self.horizontalLayout_2.addWidget(self.clean_b)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)

        self.retranslateUi(In_dev_infor)
        self.fin_b.clicked.connect(In_dev_infor.click_fin_b)
        self.exit_b.clicked.connect(In_dev_infor.reject)
        self.clean_b.clicked.connect(self.v_reso_x.clear)
        self.clean_b.clicked.connect(self.v_reso_y.clear)
        self.clean_b.clicked.connect(self.v_p_name.clear)
        self.clean_b.clicked.connect(self.v_a_name.clear)
        QtCore.QMetaObject.connectSlotsByName(In_dev_infor)

    def retranslateUi(self, In_dev_infor):
        _translate = QtCore.QCoreApplication.translate
        In_dev_infor.setWindowTitle(_translate("In_dev_infor", "Dialog"))
        self.reso_x.setText(_translate("In_dev_infor", "分辨率X值："))
        self.reso_y.setText(_translate("In_dev_infor", "分辨率Y值："))
        self.p_name.setText(_translate("In_dev_infor", "应用的包名："))
        self.a_name.setText(_translate("In_dev_infor", "应用的活动名："))
        self.fin_b.setText(_translate("In_dev_infor", "输入完毕"))
        self.exit_b.setText(_translate("In_dev_infor", "退出"))
        self.clean_b.setText(_translate("In_dev_infor", "清屏"))

