# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TestWindow(object):
    def setupUi(self, TestWindow):
        TestWindow.setObjectName("TestWindow")
        TestWindow.resize(1036, 844)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TestWindow.sizePolicy().hasHeightForWidth())
        TestWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(TestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 350, 1011, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.queue_list = QtWidgets.QWidget()
        self.queue_list.setObjectName("queue_list")
        self.queueList = QtWidgets.QListWidget(self.queue_list)
        self.queueList.setGeometry(QtCore.QRect(10, 20, 731, 331))
        self.queueList.setObjectName("queueList")
        self.tabWidget.addTab(self.queue_list, "")
        self.report_list = QtWidgets.QWidget()
        self.report_list.setObjectName("report_list")
        self.reportList = QtWidgets.QListWidget(self.report_list)
        self.reportList.setGeometry(QtCore.QRect(10, 20, 731, 331))
        self.reportList.setObjectName("reportList")
        self.tabWidget.addTab(self.report_list, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loadButton.setEnabled(False)
        self.loadButton.setMinimumSize(QtCore.QSize(250, 40))
        self.loadButton.setMaximumSize(QtCore.QSize(250, 40))
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout.addWidget(self.loadButton)
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setMinimumSize(QtCore.QSize(250, 40))
        self.saveButton.setMaximumSize(QtCore.QSize(250, 40))
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.startButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startButton.setEnabled(False)
        self.startButton.setMinimumSize(QtCore.QSize(250, 40))
        self.startButton.setMaximumSize(QtCore.QSize(250, 40))
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.p_r_s = QtWidgets.QVBoxLayout()
        self.p_r_s.setObjectName("p_r_s")
        self.pauseButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pauseButton.setMinimumSize(QtCore.QSize(250, 40))
        self.pauseButton.setMaximumSize(QtCore.QSize(250, 40))
        self.pauseButton.setObjectName("pauseButton")
        self.p_r_s.addWidget(self.pauseButton)
        self.resumeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.resumeButton.setEnabled(False)
        self.resumeButton.setMinimumSize(QtCore.QSize(250, 40))
        self.resumeButton.setMaximumSize(QtCore.QSize(250, 40))
        self.resumeButton.setObjectName("resumeButton")
        self.p_r_s.addWidget(self.resumeButton)
        self.stopButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stopButton.setMinimumSize(QtCore.QSize(250, 40))
        self.stopButton.setMaximumSize(QtCore.QSize(250, 40))
        self.stopButton.setObjectName("stopButton")
        self.p_r_s.addWidget(self.stopButton)
        self.verticalLayout_2.addLayout(self.p_r_s)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        self.testButton.setGeometry(QtCore.QRect(470, 770, 75, 23))
        self.testButton.setObjectName("testButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 110, 911, 181))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.connectDeviceButton = QtWidgets.QPushButton(self.widget)
        self.connectDeviceButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectDeviceButton.sizePolicy().hasHeightForWidth())
        self.connectDeviceButton.setSizePolicy(sizePolicy)
        self.connectDeviceButton.setMinimumSize(QtCore.QSize(321, 41))
        self.connectDeviceButton.setMaximumSize(QtCore.QSize(321, 41))
        self.connectDeviceButton.setObjectName("connectDeviceButton")
        self.gridLayout.addWidget(self.connectDeviceButton, 0, 0, 1, 1)
        self.InputAssignmentButton = QtWidgets.QPushButton(self.widget)
        self.InputAssignmentButton.setEnabled(False)
        self.InputAssignmentButton.setMinimumSize(QtCore.QSize(321, 41))
        self.InputAssignmentButton.setMaximumSize(QtCore.QSize(321, 41))
        self.InputAssignmentButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.InputAssignmentButton.setMouseTracking(False)
        self.InputAssignmentButton.setAutoDefault(False)
        self.InputAssignmentButton.setDefault(False)
        self.InputAssignmentButton.setFlat(False)
        self.InputAssignmentButton.setObjectName("InputAssignmentButton")
        self.gridLayout.addWidget(self.InputAssignmentButton, 0, 1, 1, 1)
        self.addPointButton = QtWidgets.QPushButton(self.widget)
        self.addPointButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPointButton.sizePolicy().hasHeightForWidth())
        self.addPointButton.setSizePolicy(sizePolicy)
        self.addPointButton.setMinimumSize(QtCore.QSize(321, 41))
        self.addPointButton.setMaximumSize(QtCore.QSize(321, 41))
        self.addPointButton.setObjectName("addPointButton")
        self.gridLayout.addWidget(self.addPointButton, 1, 0, 1, 1)
        self.chooseTypeButton = QtWidgets.QPushButton(self.widget)
        self.chooseTypeButton.setEnabled(False)
        self.chooseTypeButton.setMinimumSize(QtCore.QSize(321, 41))
        self.chooseTypeButton.setMaximumSize(QtCore.QSize(321, 41))
        self.chooseTypeButton.setObjectName("chooseTypeButton")
        self.gridLayout.addWidget(self.chooseTypeButton, 1, 1, 1, 1)
        TestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        TestWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TestWindow)
        self.statusbar.setObjectName("statusbar")
        TestWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(TestWindow)
        self.tabWidget.setCurrentIndex(0)
        self.chooseTypeButton.clicked.connect(TestWindow.click_add_test)
        self.startButton.clicked.connect(self.loadButton.hide)
        self.startButton.clicked.connect(self.pauseButton.show)
        self.startButton.clicked.connect(self.saveButton.hide)
        self.startButton.clicked.connect(self.saveButton.hide)
        self.startButton.clicked.connect(self.startButton.hide)
        self.startButton.clicked.connect(self.pauseButton.show)
        self.startButton.clicked.connect(self.resumeButton.show)
        self.startButton.clicked.connect(self.stopButton.show)
        self.stopButton.clicked.connect(self.loadButton.show)
        self.stopButton.clicked.connect(self.saveButton.show)
        self.stopButton.clicked.connect(self.startButton.show)
        self.stopButton.clicked.connect(self.pauseButton.hide)
        self.stopButton.clicked.connect(self.resumeButton.hide)
        self.stopButton.clicked.connect(self.stopButton.hide)
        self.loadButton.clicked.connect(TestWindow.click_load_b)
        self.saveButton.clicked.connect(TestWindow.click_save_b)
        self.startButton.clicked.connect(TestWindow.click_start_b)
        self.pauseButton.clicked.connect(TestWindow.click_pause_b)
        self.resumeButton.clicked.connect(TestWindow.click_resume_b)
        self.stopButton.clicked.connect(TestWindow.click_stop_b)
        self.connectDeviceButton.clicked.connect(TestWindow.click_connect_b)
        self.InputAssignmentButton.clicked.connect(TestWindow.click_in_index_b)
        self.addPointButton.clicked.connect(TestWindow.click_add_point_b)
        QtCore.QMetaObject.connectSlotsByName(TestWindow)

    def retranslateUi(self, TestWindow):
        _translate = QtCore.QCoreApplication.translate
        TestWindow.setWindowTitle(_translate("TestWindow", "测试窗口"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.queue_list), _translate("TestWindow", "测试队列"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.report_list), _translate("TestWindow", "测试报告"))
        self.loadButton.setText(_translate("TestWindow", "读取存档"))
        self.saveButton.setText(_translate("TestWindow", "保存测试"))
        self.startButton.setText(_translate("TestWindow", "开始测试"))
        self.pauseButton.setText(_translate("TestWindow", "暂停测试"))
        self.resumeButton.setText(_translate("TestWindow", "继续测试"))
        self.stopButton.setText(_translate("TestWindow", "终止测试"))
        self.testButton.setText(_translate("TestWindow", "测试按钮"))
        self.connectDeviceButton.setText(_translate("TestWindow", "连接设备"))
        self.InputAssignmentButton.setText(_translate("TestWindow", "输入要测试的app参数"))
        self.addPointButton.setText(_translate("TestWindow", "添加屏幕上的点"))
        self.chooseTypeButton.setText(_translate("TestWindow", "选择测试并加入测试队列"))
        self.menu.setTitle(_translate("TestWindow", "帮助"))

