# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TestWindow(object):
    def setupUi(self, TestWindow):
        TestWindow.setObjectName("TestWindow")
        TestWindow.resize(1073, 816)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TestWindow.sizePolicy().hasHeightForWidth())
        TestWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(TestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 350, 1011, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.queue_list = QtWidgets.QWidget()
        self.queue_list.setObjectName("queue_list")
        self.listWidget_3 = QtWidgets.QListWidget(self.queue_list)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 20, 731, 331))
        self.listWidget_3.setObjectName("listWidget_3")
        self.tabWidget.addTab(self.queue_list, "")
        self.report_list = QtWidgets.QWidget()
        self.report_list.setObjectName("report_list")
        self.listWidget_2 = QtWidgets.QListWidget(self.report_list)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 20, 731, 331))
        self.listWidget_2.setObjectName("listWidget_2")
        self.tabWidget.addTab(self.report_list, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_b = QtWidgets.QPushButton(self.layoutWidget)
        self.load_b.setMinimumSize(QtCore.QSize(250, 40))
        self.load_b.setMaximumSize(QtCore.QSize(250, 40))
        self.load_b.setObjectName("load_b")
        self.verticalLayout.addWidget(self.load_b)
        self.save_b = QtWidgets.QPushButton(self.layoutWidget)
        self.save_b.setMinimumSize(QtCore.QSize(250, 40))
        self.save_b.setMaximumSize(QtCore.QSize(250, 40))
        self.save_b.setObjectName("save_b")
        self.verticalLayout.addWidget(self.save_b)
        self.start_b = QtWidgets.QPushButton(self.layoutWidget)
        self.start_b.setMinimumSize(QtCore.QSize(250, 40))
        self.start_b.setMaximumSize(QtCore.QSize(250, 40))
        self.start_b.setObjectName("start_b")
        self.verticalLayout.addWidget(self.start_b)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.p_r_s = QtWidgets.QVBoxLayout()
        self.p_r_s.setObjectName("p_r_s")
        self.pause_b = QtWidgets.QPushButton(self.layoutWidget)
        self.pause_b.setMinimumSize(QtCore.QSize(250, 40))
        self.pause_b.setMaximumSize(QtCore.QSize(250, 40))
        self.pause_b.setObjectName("pause_b")
        self.p_r_s.addWidget(self.pause_b)
        self.resume_b = QtWidgets.QPushButton(self.layoutWidget)
        self.resume_b.setMinimumSize(QtCore.QSize(250, 40))
        self.resume_b.setMaximumSize(QtCore.QSize(250, 40))
        self.resume_b.setObjectName("resume_b")
        self.p_r_s.addWidget(self.resume_b)
        self.stop_b = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_b.setMinimumSize(QtCore.QSize(250, 40))
        self.stop_b.setMaximumSize(QtCore.QSize(250, 40))
        self.stop_b.setObjectName("stop_b")
        self.p_r_s.addWidget(self.stop_b)
        self.verticalLayout_2.addLayout(self.p_r_s)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 31, 992, 291))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(990, 200))
        self.label.setMaximumSize(QtCore.QSize(990, 200))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connectDeviceButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectDeviceButton.sizePolicy().hasHeightForWidth())
        self.connectDeviceButton.setSizePolicy(sizePolicy)
        self.connectDeviceButton.setMinimumSize(QtCore.QSize(321, 41))
        self.connectDeviceButton.setMaximumSize(QtCore.QSize(321, 41))
        self.connectDeviceButton.setObjectName("connectDeviceButton")
        self.horizontalLayout_2.addWidget(self.connectDeviceButton)
        self.InputAssignmentButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.InputAssignmentButton.setMinimumSize(QtCore.QSize(321, 41))
        self.InputAssignmentButton.setMaximumSize(QtCore.QSize(321, 41))
        self.InputAssignmentButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.InputAssignmentButton.setMouseTracking(False)
        self.InputAssignmentButton.setAutoDefault(False)
        self.InputAssignmentButton.setDefault(False)
        self.InputAssignmentButton.setFlat(False)
        self.InputAssignmentButton.setObjectName("InputAssignmentButton")
        self.horizontalLayout_2.addWidget(self.InputAssignmentButton)
        self.chooseTypeButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.chooseTypeButton.setMinimumSize(QtCore.QSize(321, 41))
        self.chooseTypeButton.setMaximumSize(QtCore.QSize(321, 41))
        self.chooseTypeButton.setObjectName("chooseTypeButton")
        self.horizontalLayout_2.addWidget(self.chooseTypeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        TestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1073, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        TestWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TestWindow)
        self.statusbar.setObjectName("statusbar")
        TestWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(TestWindow)
        self.tabWidget.setCurrentIndex(0)
        self.chooseTypeButton.clicked.connect(TestWindow.click_add_test)
        self.start_b.clicked.connect(self.load_b.hide)
        self.start_b.clicked.connect(self.pause_b.show)
        self.start_b.clicked.connect(self.save_b.hide)
        self.start_b.clicked.connect(self.save_b.hide)
        self.start_b.clicked.connect(self.start_b.hide)
        self.start_b.clicked.connect(self.pause_b.show)
        self.start_b.clicked.connect(self.resume_b.show)
        self.start_b.clicked.connect(self.stop_b.show)
        self.stop_b.clicked.connect(self.load_b.show)
        self.stop_b.clicked.connect(self.save_b.show)
        self.stop_b.clicked.connect(self.start_b.show)
        self.stop_b.clicked.connect(self.pause_b.hide)
        self.stop_b.clicked.connect(self.resume_b.hide)
        self.stop_b.clicked.connect(self.stop_b.hide)
        self.load_b.clicked.connect(TestWindow.click_load_b)
        self.save_b.clicked.connect(TestWindow.click_save_b)
        self.start_b.clicked.connect(TestWindow.click_start_b)
        self.pause_b.clicked.connect(TestWindow.click_pause_b)
        self.resume_b.clicked.connect(TestWindow.click_resume_b)
        self.stop_b.clicked.connect(TestWindow.click_stop_b)
        self.connectDeviceButton.clicked.connect(TestWindow.click_connect_b)
        self.InputAssignmentButton.clicked.connect(TestWindow.click_in_index_b)
        QtCore.QMetaObject.connectSlotsByName(TestWindow)

    def retranslateUi(self, TestWindow):
        _translate = QtCore.QCoreApplication.translate
        TestWindow.setWindowTitle(_translate("TestWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.queue_list), _translate("TestWindow", "测试队列"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.report_list), _translate("TestWindow", "测试报告"))
        self.load_b.setText(_translate("TestWindow", "读取存档"))
        self.save_b.setText(_translate("TestWindow", "保存测试"))
        self.start_b.setText(_translate("TestWindow", "开始测试"))
        self.pause_b.setText(_translate("TestWindow", "暂停测试"))
        self.resume_b.setText(_translate("TestWindow", "继续测试"))
        self.stop_b.setText(_translate("TestWindow", "终止测试"))
        self.label.setText(_translate("TestWindow", "TextLabel"))
        self.connectDeviceButton.setText(_translate("TestWindow", "连接设备"))
        self.InputAssignmentButton.setText(_translate("TestWindow", "输入要测试的app参数"))
        self.chooseTypeButton.setText(_translate("TestWindow", "选择测试并加入测试队列"))
        self.menu.setTitle(_translate("TestWindow", "帮助"))

