# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 767)
        MainWindow.setMinimumSize(QtCore.QSize(1, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("image: url(:/newPrefix/c0d98682b9014a9005ae5bd5a9773912b21bee11.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.guide_b = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guide_b.sizePolicy().hasHeightForWidth())
        self.guide_b.setSizePolicy(sizePolicy)
        self.guide_b.setMinimumSize(QtCore.QSize(339, 100))
        self.guide_b.setMaximumSize(QtCore.QSize(339, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.guide_b.setFont(font)
        self.guide_b.setStyleSheet("")
        self.guide_b.setObjectName("guide_b")
        self.gridLayout.addWidget(self.guide_b, 1, 0, 1, 1)
        self.test_b = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_b.sizePolicy().hasHeightForWidth())
        self.test_b.setSizePolicy(sizePolicy)
        self.test_b.setMinimumSize(QtCore.QSize(339, 100))
        self.test_b.setMaximumSize(QtCore.QSize(339, 100))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.test_b.setFont(font)
        self.test_b.setStyleSheet("")
        self.test_b.setIconSize(QtCore.QSize(20, 20))
        self.test_b.setCheckable(False)
        self.test_b.setObjectName("test_b")
        self.gridLayout.addWidget(self.test_b, 0, 0, 1, 1)
        self.feedback_b = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feedback_b.sizePolicy().hasHeightForWidth())
        self.feedback_b.setSizePolicy(sizePolicy)
        self.feedback_b.setMinimumSize(QtCore.QSize(339, 100))
        self.feedback_b.setMaximumSize(QtCore.QSize(339, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.feedback_b.setFont(font)
        self.feedback_b.setObjectName("feedback_b")
        self.gridLayout.addWidget(self.feedback_b, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.test_b.clicked.connect(MainWindow.click_button_1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.guide_b.setText(_translate("MainWindow", "引导"))
        self.test_b.setText(_translate("MainWindow", "测试(目前点击会关闭窗口)"))
        self.feedback_b.setText(_translate("MainWindow", "反馈"))

import images.test_picture
